    #######################################
    ##             端口配置               ##
    #######################################
server:
  port: 8080

spring:
    #######################################
    ##             MySQL配置             ##
    #######################################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/ssm_layui?useSSL=false&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #######################################
    ##             Druid配置             ##
    #######################################
    # 初始化大小,最小,最大
    initialSize: 1
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # IP白名单
    druidAllow:
    # IP黑名单
    druidDeny:
    # 登录druid的账号
    druidLoginName: druid
    # 登录druid的密码
    druidPassword: 123456
    #######################################
    ##             Redis配置             ##
    #######################################
  redis:
    # Redis数据库索引(默认为0)
    database: 0
    host: localhost
    port: 6379
    password:
    # 连接超时时间(毫秒)
    timeout: 0
    pool:
      # 连接池最大连接数(使用负值表示没有限制)
      max-active: 8
      # 连接池最大阻塞等待时间(使用负值表示没有限制)
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 集群配置
    cluster:
      nodes:
      max-redirects:
    # 哨兵模式
    sentinel:
      master:
      nodes:

  #######################################
  ##             Thymleaf配置          ##
  #######################################
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /resources/static/**

    #######################################
    ##             Mybatis配置           ##
    #######################################
mybatis:
  mapperLocations: classpath:com/ch/dao/*.xml
  typeAliasesPackage: com.ch.dao
  configLocation: classpath:/mybatis-config.xml

    #######################################
    ##             Shiro配置             ##
    #######################################
shiro:
  loginUrl: /
  successUrl: /index
  unauthorizedUrl: /403
  filterChainDefinitions: /resources/static/**=anon;/index=authc;/user/**=authc;/role/**=authc;/menu/**=authc
